# [𝝺] Low-level functional API

## Functional evolution

First let's set up a module to play with:

In [1]:
# - Switch off warnings
import warnings

warnings.filterwarnings("ignore")

# - Rockpool imports
from rockpool.nn.modules import RateJax

# - Other useful imports
import numpy as np

try:
    from rich import print
except:
    pass

# - Construct a module
N = 3
mod = RateJax(N)

Now if we evolve the module, we get the outputs we expect:

In [2]:
# - Set up some input
T = 10
input = np.random.rand(T, N)
output, new_state, record = mod(input)

In [3]:
print("output:", output)

output: [[[0.01076346 0.02204564 0.02956902]
  [0.04010231 0.06479559 0.07025937]
  [0.0432203  0.06293815 0.11122491]
  [0.06027619 0.08317991 0.1307195 ]
  [0.05882018 0.09205481 0.15850767]
  [0.08602361 0.12148949 0.16591538]
  [0.10797263 0.11710763 0.18505278]
  [0.13634151 0.13502166 0.20233528]
  [0.15542242 0.15269144 0.20374872]
  [0.16027772 0.15767853 0.19997193]]]

In [4]:
print("new_state:", new_state)

new_state:
{
    'x': DeviceArray([0.16027772, 0.15767853, 0.19997193], dtype=float32),
    'rng_key': DeviceArray([2469880657, 3700232383], dtype=uint32)
}

In [5]:
print("mod.state:", mod.state())
print(mod.state()["x"], " != ", new_state["x"])

mod.state:
{
    'rng_key': DeviceArray([ 237268104, 2681681569], dtype=uint32),
    'x': DeviceArray([0., 0., 0.], dtype=float32)
}

[0. 0. 0.]  !=  [0.16027772 0.15767853 0.19997193]

In [6]:
mod = mod.set_attributes(new_state)
print(mod.state()["x"], " == ", new_state["x"])

[0.16027772 0.15767853 0.19997193]  ==  [0.16027772 0.15767853 0.19997193]

## Functional state and attribute setting

In [7]:
new_tau = mod.tau * 0.4
mod.tau = new_tau
print(new_tau, " == ", mod.tau)

[0.008 0.008 0.008]  ==  [0.008 0.008 0.008]

In [8]:
params = mod.parameters()
params["tau"] = params["tau"] * 3.0

# - Note the functional calling style
mod = mod.set_attributes(params)

# - check that the attribute was set
print(params["tau"], " == ", mod.tau)

[0.024 0.024 0.024]  ==  [0.024 0.024 0.024]

## Functional module reset

In [9]:
# - Reset the module state
mod = mod.reset_state()

# - Reset the module parameters
mod = mod.reset_parameters()

## Jax flattening