# 🛠 Low-level `Module` API

## Constructing a `Module`

In [1]:
# - Switch off warnings
import warnings

warnings.filterwarnings("ignore")

# - Useful imports
try:
    from rich import print
except:
    pass

# - Example of constructing a module
from rockpool.nn.modules import Rate
import numpy as np

# - Construct a Module with 4 neurons
mod = Rate(4)
print(mod)

Could not import package: No module named 'iaf_nest'


Rate  with shape (4,)

In [2]:
# - Construct a Module with concrete parameters
mod = Rate(4, tau=np.ones(4))
print(mod)

Rate  with shape (4,)

## Evolving a `Module`

In [3]:
# - Generate and evolve over some input
T = 5
input = np.random.rand(T, mod.size_in)
output, _, _ = mod(input)
print(f"Output shape: {output.shape}")

Output shape: (1, 5, 4)

In [4]:
# - Request the recorded state
output, _, recorded_state = mod(input, record=True)
print("Parameters:", recorded_state)

Parameters:
{
    'rec_input': array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]]),
    'x': array([[[0.00208988, 0.00269727, 0.00268279, 0.00087984],
        [0.0025245 , 0.00278765, 0.00294062, 0.00100819],
        [0.00289478, 0.00326989, 0.00337313, 0.00119108],
        [0.00316175, 0.00351731, 0.00387368, 0.00127133],
        [0.00385746, 0.00438043, 0.00476745, 0.00159747]]])
}

## Parameters, State and SimulationParameters

## Building a network with `Module` s

In [5]:
# - Build a simple network
from rockpool.nn.modules import Module
from rockpool.parameters import Parameter
from rockpool.nn.modules import RateJax


class ffwd_net(Module):
    # - Provide an `__init__` method to specify required parameters and modules
    #   Here you check, define and initialise whatever parameters and
    #   state you need for your module.
    def __init__(
        self,
        shape,
        *args,
        **kwargs,
    ):
        # - Call superclass initialisation
        #   This is always required for a `Module` class
        super().__init__(shape=shape, *args, **kwargs)

        # - Specify weights attribute
        #   We need a weights matrix for our input weights.
        #   We specify the shape explicitly, and provide an initialisation function.
        #   We also specify a family for the parameter, "weights". This is used to
        #   query parameters conveniently, and is a good idea to provide.
        self.w_ffwd = Parameter(
            shape=self.shape,
            init_func=lambda s: np.zeros(s),
            family="weights",
        )

        # - Specify and a add submodule
        #   These will be the neurons in our layer, to receive the weighted
        #   input signals. This sub-module will be automatically configured
        #   internally, to specify the required state and parameters
        self.neurons = RateJax(self.shape[-1])

    # - The `evolve` method contains the internal logic of your module
    #   `evolve` takes care of passing data in and out of the module,
    #   and between sub-modules if present.
    def evolve(self, input_data, *args, **kwargs):
        # - Pass input data through the input weights
        x = input_data @ self.w_ffwd

        # - Pass the signals through the neurons
        x, _, _ = self.neurons(x)

        # - Return the module output
        return x, {}, {}

### Writing an `evolve()` method that returns state and record

In [6]:
def evolve(self, input_data, record: bool = False, *args, **kwargs):
    # - Initialise state and record dictionaries
    new_state = {}
    recorded_state = {}

    # - Pass input data through the input weights
    x = input_data @ self.w_ffwd

    # - Add an internal signal record to the record dictionary
    if record:
        recorded_state["weighted_input"] = x

    # - Pass the signals through the neurons, passing through the `record` argument
    x, submod_state, submod_record = self.neurons(x, record=record)

    # - Record the submodule state
    new_state.update("neurons", submod_state)

    # - Include the recorded state
    recorded_state.update("neurons", submod_record)

    # - Return the module output
    return x, new_state, recorded_state

## Inspecting a `Module`

In [7]:
# - Build a module for our network
my_mod = ffwd_net((4, 6))
print(my_mod)

ffwd_net  with shape (4, 6) {
    RateJax 'neurons' with shape (6,)
}

In [8]:
# - Show module parameters
print("Parameters:", my_mod.parameters())

Parameters:
{
    'w_ffwd': array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]]),
    'neurons': {
        'tau': DeviceArray([0.02, 0.02, 0.02, 0.02, 0.02, 0.02], dtype=float32),
        'bias': DeviceArray([0., 0., 0., 0., 0., 0.], dtype=float32),
        'threshold': DeviceArray([0., 0., 0., 0., 0., 0.], dtype=float32)
    }
}

In [9]:
# - Show module state
print("State:", my_mod.state())

State:
{
    'neurons': {
        'rng_key': array([1281508172, 2932039378], dtype=uint32),
        'x': DeviceArray([0., 0., 0., 0., 0., 0.], dtype=float32)
    }
}

In [10]:
# - Return parameters from particular families
print("Module time constants:", my_mod.parameters("taus"))
print("Module weights:", my_mod.parameters("weights"))

Module time constants:
{'neurons': {'tau': DeviceArray([0.02, 0.02, 0.02, 0.02, 0.02, 0.02], dtype=float32)}}

Module weights:
{
    'w_ffwd': array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])
}

In [11]:
# - Access parameters directly
print(".w_ffwd:", my_mod.w_ffwd)
print(".neurons.tau:", my_mod.neurons.tau)

.w_ffwd: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

.neurons.tau: [0.02 0.02 0.02 0.02 0.02 0.02]

## `Module` API reference