In [1]:
import numpy as np
from rockpool.devices.dynapse import BiasGen

In [2]:
print(BiasGen.coarse_base)
print(BiasGen.get_coarse_fine(1000000, coarse_smallest = True, exact=True))
print(BiasGen.get_coarse_fine(1000000, coarse_smallest = True, exact=False))
print(BiasGen.get_coarse_fine(1000000, coarse_smallest = False, exact=True))
print(BiasGen.get_coarse_fine(1000000, coarse_smallest = False, exact=False))
##
print(BiasGen.get_linear(4,51))
print(BiasGen.get_linear(5,6))

[1.50e-11 1.05e-10 8.20e-10 6.50e-09 5.00e-08 4.00e-07 3.20e-06 2.40e-05]
(4, 51)
(4, 51)
(4, 51)
(5, 6)
1000000.0
941176.0


In [15]:
def test_coarse_fine():
    for c in range(8):
        for f in range(0, 256):
            linear = BiasGen.get_linear(c,f)
            coarse, fine = BiasGen.get_coarse_fine(linear)
            STR = f"Bias current = {linear} (*1e-14), can be obtained with either:{c, f} or {coarse,fine}"
            try:
                assert c == coarse, STR
                assert f == fine, STR
            except AssertionError as e:
                linear1 = BiasGen.get_linear(c,f)
                linear2 = BiasGen.get_linear(coarse,fine)
                print(e)
                str_not_equal = f"Bias current {c,f,linear1} != {coarse,fine,linear2}"
                assert linear1 == linear2, str_not_equal
            
        
test_coarse_fine()


Bias current = 0.0 (*1e-14), can be obtained with either:(1, 0) or (0, 0)
Bias current = 41.0 (*1e-14), can be obtained with either:(1, 1) or (0, 7)
Bias current = 82.0 (*1e-14), can be obtained with either:(1, 2) or (0, 14)
Bias current = 124.0 (*1e-14), can be obtained with either:(1, 3) or (0, 21)
Bias current = 165.0 (*1e-14), can be obtained with either:(1, 4) or (0, 28)
Bias current = 206.0 (*1e-14), can be obtained with either:(1, 5) or (0, 35)
Bias current = 247.0 (*1e-14), can be obtained with either:(1, 6) or (0, 42)
Bias current = 288.0 (*1e-14), can be obtained with either:(1, 7) or (0, 49)
Bias current = 329.0 (*1e-14), can be obtained with either:(1, 8) or (0, 56)
Bias current = 371.0 (*1e-14), can be obtained with either:(1, 9) or (0, 63)
Bias current = 412.0 (*1e-14), can be obtained with either:(1, 10) or (0, 70)
Bias current = 453.0 (*1e-14), can be obtained with either:(1, 11) or (0, 77)
Bias current = 494.0 (*1e-14), can be obtained with either:(1, 12) or (0, 84)
Bi

In [10]:
!wget https://gitlab.com/neuroinf/ctxctl_contrib/-/raw/d7543c870fa027c72ebb62f20b0f45f6638b00db/linear_fine_coarse_bias_map.npy
lookup_dimitrii = np.load('linear_fine_coarse_bias_map.npy').astype(np.float32)

--2021-09-02 18:23:18--  https://gitlab.com/neuroinf/ctxctl_contrib/-/raw/d7543c870fa027c72ebb62f20b0f45f6638b00db/linear_fine_coarse_bias_map.npy
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43616 (43K) [application/octet-stream]
Saving to: ‘linear_fine_coarse_bias_map.npy.4’

linear_fine_coarse_ 100%[===================>]  42,59K  --.-KB/s    in 0,01s   

2021-09-02 18:23:18 (2,94 MB/s) - ‘linear_fine_coarse_bias_map.npy.4’ saved [43616/43616]



In [11]:
cfl = BiasGen.get_lookup_table()
try:
    np.testing.assert_array_equal(lookup_dimitrii, cfl, verbose=True)
except AssertionError as e:
    print(e)


Arrays are not equal

Mismatched elements: 296 / 5436 (5.45%)
Max absolute difference: 256.
Max relative difference: 5.16193e-06
 x: array([[0.000000e+00, 0.000000e+00, 0.000000e+00],
       [0.000000e+00, 1.000000e+00, 6.000000e+00],
       [0.000000e+00, 2.000000e+00, 1.200000e+01],...
 y: array([[0.000000e+00, 0.000000e+00, 0.000000e+00],
       [0.000000e+00, 1.000000e+00, 6.000000e+00],
       [0.000000e+00, 2.000000e+00, 1.200000e+01],...


In [12]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [13]:
cfl[-1]

array([7.00e+00, 2.55e+02, 2.40e+09], dtype=float32)

In [14]:
lookup_dimitrii[-1]

array([7.00e+00, 2.55e+02, 2.40e+09], dtype=float32)